### ISSUE TITLE
Where is the algorithm

### ISSUE THREAD

**Issue by mghifariyusuf** [magiclen/node-fast-string-search#1]
Nice package. How I can see the source code of boyer moore algorithm? In which file it has been?

**Comment by magiclen** [comment]
The src folder has only one file named `fast-string-search.c`. You can see the implementation of *boyer-moore-magiclen*.

**Comment by mghifariyusuf** [comment]
oh you write code in C programming language?

**Comment by magiclen** [comment]
yes, of course

**Comment by magiclen** [comment]
If you are interested in this algorithm, you can read [my article](https://magiclen.org/boyer-moore-magiclen).
